#%RAML 1.0 Trait
headers:
  client_id:
    type: string
    required: true
    example: "897348hefej9847r9847"
  client_secret:
    type: string
    required: true
    example: "dkfjkdahs87894784nvsb"  